apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kuber-test
  template:
    metadata:
      labels:
        app: kuber-test
    spec:
      containers:
      - name: kuber-test
        image: kuber-test
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        readinessProbe: #готовность
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 2
        livenessProbe: # жива ли проба
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 2